// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct IpUtilizationInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  public var subnetIpUtilization: [IpUtilizationInfo.SubnetIpUtilization] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `IpUtilizationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpUtilizationInfo().with { $0.subnetIpUtilization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let subnetIpUtilization = CodingKeys(stringValue: "subnetIpUtilization")

    static let _knownKeys: Set<Swift.String> = [
      "subnetIpUtilization"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [IpUtilizationInfo.SubnetIpUtilization].self, forKey: .subnetIpUtilization)
    {
      self.subnetIpUtilization = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.subnetIpUtilization, forKey: .subnetIpUtilization)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public struct SubnetIpUtilization: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// URI of subnet.
    public var subnetUri: Swift.String = Swift.String()

    /// Secondary range name. If the range is the primary range of the subnet,
    /// this field is empty.
    public var secondaryRangeName: Swift.String = Swift.String()

    /// Total number of usable IP addresses in the IP range.
    public var totalUsableAddresses: Swift.UInt64 = Swift.UInt64()

    /// The ratio of allocated IP addresses from the total usable addresses.
    public var allocationRatio: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SubnetIpUtilization`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubnetIpUtilization().with { $0.subnetUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let subnetUri = CodingKeys(stringValue: "subnetUri")
      static let secondaryRangeName = CodingKeys(stringValue: "secondaryRangeName")
      static let totalUsableAddresses = CodingKeys(stringValue: "totalUsableAddresses")
      static let allocationRatio = CodingKeys(stringValue: "allocationRatio")

      static let _knownKeys: Set<Swift.String> = [
        "subnetUri",
        "secondaryRangeName",
        "totalUsableAddresses",
        "allocationRatio",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetUri) {
        self.subnetUri = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryRangeName) {
        self.secondaryRangeName = value
      }
      if let value = try container.decodeIfPresent(Swift.UInt64.self, forKey: .totalUsableAddresses)
      {
        self.totalUsableAddresses = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .allocationRatio) {
        self.allocationRatio = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.subnetUri, forKey: .subnetUri)
      try container.encode(self.secondaryRangeName, forKey: .secondaryRangeName)
      try container.encode(self.totalUsableAddresses, forKey: .totalUsableAddresses)
      try container.encode(self.allocationRatio, forKey: .allocationRatio)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkanalyzer.logging.v1.IpUtilizationInfo.SubnetIpUtilization"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkanalyzer.logging.v1.IpUtilizationInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
