// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

public struct IpUtilizationInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var subnetIpUtilization: [IpUtilizationInfo.SubnetIpUtilization] = []

  /// Initialize a new instance of `IpUtilizationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpUtilizationInfo().with { $0.subnetIpUtilization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public struct SubnetIpUtilization: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// URI of subnet.
    public var subnetUri: Swift.String = Swift.String()

    /// Secondary range name. If the range is the primary range of the subnet,
    /// this field is empty.
    public var secondaryRangeName: Swift.String = Swift.String()

    /// Total number of usable IP addresses in the IP range.
    public var totalUsableAddresses: Swift.UInt64 = Swift.UInt64()

    /// The ratio of allocated IP addresses from the total usable addresses.
    public var allocationRatio: Swift.Double = Swift.Double()

    /// Initialize a new instance of `SubnetIpUtilization`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubnetIpUtilization().with { $0.subnetUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networkanalyzer.logging.v1.IpUtilizationInfo.SubnetIpUtilization"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkanalyzer.logging.v1.IpUtilizationInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
