// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log entry that describes a report from Network Analyzer.
public struct Report: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The unique identifier of the report.
  public var id: Swift.String = Swift.String()

  /// Priority of the report.
  public var priority: Report.Priority = Report.Priority()

  /// Type of the report.
  public var type: Report.Type_ = Report.Type_()

  /// Status of the report.
  public var status: Report.ReportStatus = Report.ReportStatus()

  /// The timestamp when the report was first discovered by Network Analyzer.
  public var firstReportTime: GoogleCloudWKT.Timestamp? = nil

  /// Cause code of the report.
  public var causeCode: ReportCauseCode = ReportCauseCode()

  /// The resource that are reported with the report.
  /// Contains the fully qualified resource name.
  /// e.g.,
  /// `//compute.googleapis.com/projects/{project_id}/global/networks/{network}`
  public var resourceName: Swift.String = Swift.String()

  /// Location associated with the report. It can be global or GCP regions
  /// and zones. e.g., https://cloud.google.com/compute/docs/regions-zones/
  public var location: Swift.String = Swift.String()

  /// URI to the documentation of the report.
  public var reportDocumentationUri: Swift.String = Swift.String()

  /// The groups of the report. One report may be present in multiple groups.
  public var reportGroups: [Report.ReportGroup] = []

  public var content: OneOf_Content? = nil

  /// Initialize a new instance of `Report`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Report().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case priority = "priority"
    case type = "type"
    case status = "status"
    case firstReportTime = "firstReportTime"
    case causeCode = "causeCode"
    case resourceName = "resourceName"
    case location = "location"
    case reportDocumentationUri = "reportDocumentationUri"
    case reportGroups = "reportGroups"
    case ipUtilizationInfo = "ipUtilizationInfo"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.priority = try container.decode(Report.Priority.self, forKey: .priority)
    self.type = try container.decode(Report.Type_.self, forKey: .type)
    self.status = try container.decode(Report.ReportStatus.self, forKey: .status)
    self.firstReportTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .firstReportTime)
    self.causeCode = try container.decode(ReportCauseCode.self, forKey: .causeCode)
    self.resourceName = try container.decode(Swift.String.self, forKey: .resourceName)
    self.location = try container.decode(Swift.String.self, forKey: .location)
    self.reportDocumentationUri = try container.decode(
      Swift.String.self, forKey: .reportDocumentationUri)
    self.reportGroups = try container.decode([Report.ReportGroup].self, forKey: .reportGroups)

    var content: OneOf_Content? = nil
    let contentCheckAndSet = {
      if content != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'content'"))
      }
      content = $0
    }
    if let ipUtilizationInfo = try container.decodeIfPresent(
      IpUtilizationInfo?.self, forKey: .ipUtilizationInfo)
    {
      try contentCheckAndSet(.ipUtilizationInfo(ipUtilizationInfo))
    }
    self.content = content
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.priority, forKey: .priority)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.firstReportTime, forKey: .firstReportTime)
    try container.encode(self.causeCode, forKey: .causeCode)
    try container.encode(self.resourceName, forKey: .resourceName)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.reportDocumentationUri, forKey: .reportDocumentationUri)
    try container.encode(self.reportGroups, forKey: .reportGroups)

    if let choice = self.content {
      switch choice {
      case .ipUtilizationInfo(let value):
        try container.encode(value, forKey: .ipUtilizationInfo)
      }
    }
  }

  /// Priority level of an report.
  public enum Priority: Codable, Equatable, Sendable {
    case severityUnspecified
    case critical
    case high
    case medium
    case low
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .severityUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .severityUnspecified: return 0
      case .critical: return 1
      case .high: return 2
      case .medium: return 3
      case .low: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .severityUnspecified: return "SEVERITY_UNSPECIFIED"
      case .critical: return "CRITICAL"
      case .high: return "HIGH"
      case .medium: return "MEDIUM"
      case .low: return "LOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .severityUnspecified
      case "CRITICAL": self = .critical
      case "HIGH": self = .high
      case "MEDIUM": self = .medium
      case "LOW": self = .low
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .severityUnspecified
      case 1: self = .critical
      case 2: self = .high
      case 3: self = .medium
      case 4: self = .low
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .severityUnspecified: return try container.encode(0)
      case .critical: return try container.encode(1)
      case .high: return try container.encode(2)
      case .medium: return try container.encode(3)
      case .low: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of an report.
  public enum Type_: Codable, Equatable, Sendable {
    case reportTypeUnspecified
    case info
    case warning
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .reportTypeUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .reportTypeUnspecified: return 0
      case .info: return 1
      case .warning: return 2
      case .error: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .reportTypeUnspecified: return "REPORT_TYPE_UNSPECIFIED"
      case .info: return "INFO"
      case .warning: return "WARNING"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPORT_TYPE_UNSPECIFIED": self = .reportTypeUnspecified
      case "INFO": self = .info
      case "WARNING": self = .warning
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .reportTypeUnspecified
      case 1: self = .info
      case 2: self = .warning
      case 3: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .reportTypeUnspecified: return try container.encode(0)
      case .info: return try container.encode(1)
      case .warning: return try container.encode(2)
      case .error: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Status of an report.
  public enum ReportStatus: Codable, Equatable, Sendable {
    case unspecified
    case active
    case fixed
    case dismissed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .fixed: return 2
      case .dismissed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REPORT_STATUS_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .fixed: return "FIXED"
      case .dismissed: return "DISMISSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReportStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPORT_STATUS_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "FIXED": self = .fixed
      case "DISMISSED": self = .dismissed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReportStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .fixed
      case 3: self = .dismissed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .fixed: return try container.encode(2)
      case .dismissed: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Groups of an report.
  public enum ReportGroup: Codable, Equatable, Sendable {
    case categoryUnspecified
    case vpcNetwork
    case networkServices
    case kubernetesEngine
    case hybridConnectivity
    case managedServices
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .categoryUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .categoryUnspecified: return 0
      case .vpcNetwork: return 1
      case .networkServices: return 2
      case .kubernetesEngine: return 3
      case .hybridConnectivity: return 4
      case .managedServices: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .categoryUnspecified: return "CATEGORY_UNSPECIFIED"
      case .vpcNetwork: return "VPC_NETWORK"
      case .networkServices: return "NETWORK_SERVICES"
      case .kubernetesEngine: return "KUBERNETES_ENGINE"
      case .hybridConnectivity: return "HYBRID_CONNECTIVITY"
      case .managedServices: return "MANAGED_SERVICES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReportGroup/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATEGORY_UNSPECIFIED": self = .categoryUnspecified
      case "VPC_NETWORK": self = .vpcNetwork
      case "NETWORK_SERVICES": self = .networkServices
      case "KUBERNETES_ENGINE": self = .kubernetesEngine
      case "HYBRID_CONNECTIVITY": self = .hybridConnectivity
      case "MANAGED_SERVICES": self = .managedServices
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReportGroup/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .categoryUnspecified
      case 1: self = .vpcNetwork
      case 2: self = .networkServices
      case 3: self = .kubernetesEngine
      case 4: self = .hybridConnectivity
      case 5: self = .managedServices
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .categoryUnspecified: return try container.encode(0)
      case .vpcNetwork: return try container.encode(1)
      case .networkServices: return try container.encode(2)
      case .kubernetesEngine: return try container.encode(3)
      case .hybridConnectivity: return try container.encode(4)
      case .managedServices: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_Content: Codable, Equatable, Sendable {
    indirect case ipUtilizationInfo(IpUtilizationInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkanalyzer.logging.v1.Report"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
