// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

public enum ReportCauseCode: Codable, Equatable, Sendable {
  case unspecified
  /// VPC Basics
  case routeInvalidNextHopVmIpForwardingDisabled
  case routeInvalidNextHopVmDeleted
  case routeInvalidNextHopVmStopped
  case routeInvalidNextHopIlbMisconfigured
  case routeInvalidNextHopVpnTunnelDeleted
  @available(*, deprecated)
  case routeInvalidNextHopIlbBackendIpForwardingDisabled
  case routeInvalidNextHopIlbVipNotAssigned
  case routeInvalidNextHopVmWrongNetwork
  case routeInvalidNextHopVmNonPrimaryIp
  case routeInvalidNextHopVpnTunnelNotEstablished
  case routeInvalidNextHopIpNotAssigned
  case routeInvalidNextHopForwardingRuleIpMismatch
  case routeInvalidNextHopForwardingRuleTypeInvalid
  case ipUtilizationIpAllocationRatioHigh
  /// Summary of ip utilization of all subnet ranges in the project.
  case ipUtilizationIpAllocationSummary
  /// Kubernetes Engine
  case gkeNodeToControlPlaneBlockedByRoutingIssue
  @available(*, deprecated)
  case gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall
  case gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall
  @available(*, deprecated)
  case gkeControlPlaneToNodeBlockedByRoutingIssue
  @available(*, deprecated)
  case gkeControlPlaneToNodeBlockedByIngressFirewallOnNode
  case gkeIpUtilizationPodRangesAllocationHigh
  case gkeIpUtilizationPodRangesAllocationLimitesAutoscaling
  case gkeNodeServiceAccountServiceAccountDisabled
  case gkeNodeServiceAccountDefaultServiceAccountUsed
  case gkeNodeServiceAccountBadOauthScopes
  case gkeIpMasqAgentConfigMapNotCoveringPodCidr
  case gkeIpMasqAgentCustomConfigNotCoveringPodCidr
  /// Managed Services
  @available(*, deprecated)
  case cloudSqlPrivateIpBlockedByEgressFirewall
  @available(*, deprecated)
  case cloudSqlPrivateIpBlockedByRoutingIssue
  @available(*, deprecated)
  case cloudSqlPrivateIpInstanceNotRunning
  /// Hybrid Connectivity
  case dynamicRouteShadowedFullyShadowedBySubnetRoute
  case dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
  case dynamicRouteShadowedFullyShadowedByStaticRoute
  case dynamicRouteShadowedFullyShadowedByPeeringStaticRoute
  @available(*, deprecated)
  case dynamicRouteShadowedPartiallyShadowedBySubnetRoute
  @available(*, deprecated)
  case dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute
  @available(*, deprecated)
  case dynamicRouteShadowedPartiallyShadowedByStaticRoute
  @available(*, deprecated)
  case dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute
  case dynamicRouteShadowedFullyShadowedByNccSubnetRoute
  case nccDynamicRouteShadowedFullyShadowedBySubnetRoute
  case nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
  case nccDynamicRouteShadowedFullyShadowedByStaticRoute
  /// Network Services
  case loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured
  case loadBalancerHealthCheckFirewallHealthCheckRangeBlocked
  case loadBalancerHealthCheckFirewallFirewallConfigInconsistent
  case loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked
  case loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity
  case loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .routeInvalidNextHopVmIpForwardingDisabled: return 1
    case .routeInvalidNextHopVmDeleted: return 2
    case .routeInvalidNextHopVmStopped: return 3
    case .routeInvalidNextHopIlbMisconfigured: return 4
    case .routeInvalidNextHopVpnTunnelDeleted: return 5
    case .routeInvalidNextHopIlbBackendIpForwardingDisabled: return 6
    case .routeInvalidNextHopIlbVipNotAssigned: return 7
    case .routeInvalidNextHopVmWrongNetwork: return 8
    case .routeInvalidNextHopVmNonPrimaryIp: return 9
    case .routeInvalidNextHopVpnTunnelNotEstablished: return 10
    case .routeInvalidNextHopIpNotAssigned: return 11
    case .routeInvalidNextHopForwardingRuleIpMismatch: return 12
    case .routeInvalidNextHopForwardingRuleTypeInvalid: return 13
    case .ipUtilizationIpAllocationRatioHigh: return 20
    case .ipUtilizationIpAllocationSummary: return 21
    case .gkeNodeToControlPlaneBlockedByRoutingIssue: return 201
    case .gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall: return 202
    case .gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall: return 203
    case .gkeControlPlaneToNodeBlockedByRoutingIssue: return 211
    case .gkeControlPlaneToNodeBlockedByIngressFirewallOnNode: return 212
    case .gkeIpUtilizationPodRangesAllocationHigh: return 221
    case .gkeIpUtilizationPodRangesAllocationLimitesAutoscaling: return 222
    case .gkeNodeServiceAccountServiceAccountDisabled: return 243
    case .gkeNodeServiceAccountDefaultServiceAccountUsed: return 244
    case .gkeNodeServiceAccountBadOauthScopes: return 245
    case .gkeIpMasqAgentConfigMapNotCoveringPodCidr: return 251
    case .gkeIpMasqAgentCustomConfigNotCoveringPodCidr: return 252
    case .cloudSqlPrivateIpBlockedByEgressFirewall: return 601
    case .cloudSqlPrivateIpBlockedByRoutingIssue: return 602
    case .cloudSqlPrivateIpInstanceNotRunning: return 603
    case .dynamicRouteShadowedFullyShadowedBySubnetRoute: return 801
    case .dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute: return 802
    case .dynamicRouteShadowedFullyShadowedByStaticRoute: return 803
    case .dynamicRouteShadowedFullyShadowedByPeeringStaticRoute: return 804
    case .dynamicRouteShadowedPartiallyShadowedBySubnetRoute: return 805
    case .dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute: return 806
    case .dynamicRouteShadowedPartiallyShadowedByStaticRoute: return 807
    case .dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute: return 808
    case .dynamicRouteShadowedFullyShadowedByNccSubnetRoute: return 821
    case .nccDynamicRouteShadowedFullyShadowedBySubnetRoute: return 822
    case .nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute: return 823
    case .nccDynamicRouteShadowedFullyShadowedByStaticRoute: return 824
    case .loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured: return 1001
    case .loadBalancerHealthCheckFirewallHealthCheckRangeBlocked: return 1002
    case .loadBalancerHealthCheckFirewallFirewallConfigInconsistent: return 1003
    case .loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked: return 1004
    case .loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity: return 1021
    case .loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch: return 1024
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "REPORT_CAUSE_CODE_UNSPECIFIED"
    case .routeInvalidNextHopVmIpForwardingDisabled:
      return "ROUTE_INVALID_NEXT_HOP_VM_IP_FORWARDING_DISABLED"
    case .routeInvalidNextHopVmDeleted: return "ROUTE_INVALID_NEXT_HOP_VM_DELETED"
    case .routeInvalidNextHopVmStopped: return "ROUTE_INVALID_NEXT_HOP_VM_STOPPED"
    case .routeInvalidNextHopIlbMisconfigured: return "ROUTE_INVALID_NEXT_HOP_ILB_MISCONFIGURED"
    case .routeInvalidNextHopVpnTunnelDeleted: return "ROUTE_INVALID_NEXT_HOP_VPN_TUNNEL_DELETED"
    case .routeInvalidNextHopIlbBackendIpForwardingDisabled:
      return "ROUTE_INVALID_NEXT_HOP_ILB_BACKEND_IP_FORWARDING_DISABLED"
    case .routeInvalidNextHopIlbVipNotAssigned: return "ROUTE_INVALID_NEXT_HOP_ILB_VIP_NOT_ASSIGNED"
    case .routeInvalidNextHopVmWrongNetwork: return "ROUTE_INVALID_NEXT_HOP_VM_WRONG_NETWORK"
    case .routeInvalidNextHopVmNonPrimaryIp: return "ROUTE_INVALID_NEXT_HOP_VM_NON_PRIMARY_IP"
    case .routeInvalidNextHopVpnTunnelNotEstablished:
      return "ROUTE_INVALID_NEXT_HOP_VPN_TUNNEL_NOT_ESTABLISHED"
    case .routeInvalidNextHopIpNotAssigned: return "ROUTE_INVALID_NEXT_HOP_IP_NOT_ASSIGNED"
    case .routeInvalidNextHopForwardingRuleIpMismatch:
      return "ROUTE_INVALID_NEXT_HOP_FORWARDING_RULE_IP_MISMATCH"
    case .routeInvalidNextHopForwardingRuleTypeInvalid:
      return "ROUTE_INVALID_NEXT_HOP_FORWARDING_RULE_TYPE_INVALID"
    case .ipUtilizationIpAllocationRatioHigh: return "IP_UTILIZATION_IP_ALLOCATION_RATIO_HIGH"
    case .ipUtilizationIpAllocationSummary: return "IP_UTILIZATION_IP_ALLOCATION_SUMMARY"
    case .gkeNodeToControlPlaneBlockedByRoutingIssue:
      return "GKE_NODE_TO_CONTROL_PLANE_BLOCKED_BY_ROUTING_ISSUE"
    case .gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall:
      return "GKE_NODE_TO_CONTROL_PLANE_PUBLIC_ENDPOINT_BLOCKED_BY_EGRESS_FIREWALL"
    case .gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall:
      return "GKE_NODE_TO_CONTROL_PLANE_PRIVATE_ENDPOINT_BLOCKED_BY_EGRESS_FIREWALL"
    case .gkeControlPlaneToNodeBlockedByRoutingIssue:
      return "GKE_CONTROL_PLANE_TO_NODE_BLOCKED_BY_ROUTING_ISSUE"
    case .gkeControlPlaneToNodeBlockedByIngressFirewallOnNode:
      return "GKE_CONTROL_PLANE_TO_NODE_BLOCKED_BY_INGRESS_FIREWALL_ON_NODE"
    case .gkeIpUtilizationPodRangesAllocationHigh:
      return "GKE_IP_UTILIZATION_POD_RANGES_ALLOCATION_HIGH"
    case .gkeIpUtilizationPodRangesAllocationLimitesAutoscaling:
      return "GKE_IP_UTILIZATION_POD_RANGES_ALLOCATION_LIMITES_AUTOSCALING"
    case .gkeNodeServiceAccountServiceAccountDisabled:
      return "GKE_NODE_SERVICE_ACCOUNT_SERVICE_ACCOUNT_DISABLED"
    case .gkeNodeServiceAccountDefaultServiceAccountUsed:
      return "GKE_NODE_SERVICE_ACCOUNT_DEFAULT_SERVICE_ACCOUNT_USED"
    case .gkeNodeServiceAccountBadOauthScopes: return "GKE_NODE_SERVICE_ACCOUNT_BAD_OAUTH_SCOPES"
    case .gkeIpMasqAgentConfigMapNotCoveringPodCidr:
      return "GKE_IP_MASQ_AGENT_CONFIG_MAP_NOT_COVERING_POD_CIDR"
    case .gkeIpMasqAgentCustomConfigNotCoveringPodCidr:
      return "GKE_IP_MASQ_AGENT_CUSTOM_CONFIG_NOT_COVERING_POD_CIDR"
    case .cloudSqlPrivateIpBlockedByEgressFirewall:
      return "CLOUD_SQL_PRIVATE_IP_BLOCKED_BY_EGRESS_FIREWALL"
    case .cloudSqlPrivateIpBlockedByRoutingIssue:
      return "CLOUD_SQL_PRIVATE_IP_BLOCKED_BY_ROUTING_ISSUE"
    case .cloudSqlPrivateIpInstanceNotRunning: return "CLOUD_SQL_PRIVATE_IP_INSTANCE_NOT_RUNNING"
    case .dynamicRouteShadowedFullyShadowedBySubnetRoute:
      return "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_SUBNET_ROUTE"
    case .dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute:
      return "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_SUBNET_ROUTE"
    case .dynamicRouteShadowedFullyShadowedByStaticRoute:
      return "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_STATIC_ROUTE"
    case .dynamicRouteShadowedFullyShadowedByPeeringStaticRoute:
      return "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_STATIC_ROUTE"
    case .dynamicRouteShadowedPartiallyShadowedBySubnetRoute:
      return "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_SUBNET_ROUTE"
    case .dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute:
      return "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_PEERING_SUBNET_ROUTE"
    case .dynamicRouteShadowedPartiallyShadowedByStaticRoute:
      return "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_STATIC_ROUTE"
    case .dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute:
      return "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_PEERING_STATIC_ROUTE"
    case .dynamicRouteShadowedFullyShadowedByNccSubnetRoute:
      return "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_NCC_SUBNET_ROUTE"
    case .nccDynamicRouteShadowedFullyShadowedBySubnetRoute:
      return "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_SUBNET_ROUTE"
    case .nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute:
      return "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_SUBNET_ROUTE"
    case .nccDynamicRouteShadowedFullyShadowedByStaticRoute:
      return "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_STATIC_ROUTE"
    case .loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured:
      return "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_FIREWALL_NOT_CONFIGURED"
    case .loadBalancerHealthCheckFirewallHealthCheckRangeBlocked:
      return "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_RANGE_BLOCKED"
    case .loadBalancerHealthCheckFirewallFirewallConfigInconsistent:
      return "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_FIREWALL_CONFIG_INCONSISTENT"
    case .loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked:
      return "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_RANGE_PARTIALLY_BLOCKED"
    case .loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity:
      return "LOAD_BALANCER_BEST_PRACTICES_BACKEND_SERVICE_BALANCING_MODE_BREAKS_SESSION_AFFINITY"
    case .loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch:
      return "LOAD_BALANCER_BEST_PRACTICES_BACKEND_SERVICE_HEALTH_CHECK_PORT_MISMATCH"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReportCauseCode/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "REPORT_CAUSE_CODE_UNSPECIFIED": self = .unspecified
    case "ROUTE_INVALID_NEXT_HOP_VM_IP_FORWARDING_DISABLED":
      self = .routeInvalidNextHopVmIpForwardingDisabled
    case "ROUTE_INVALID_NEXT_HOP_VM_DELETED": self = .routeInvalidNextHopVmDeleted
    case "ROUTE_INVALID_NEXT_HOP_VM_STOPPED": self = .routeInvalidNextHopVmStopped
    case "ROUTE_INVALID_NEXT_HOP_ILB_MISCONFIGURED": self = .routeInvalidNextHopIlbMisconfigured
    case "ROUTE_INVALID_NEXT_HOP_VPN_TUNNEL_DELETED": self = .routeInvalidNextHopVpnTunnelDeleted
    case "ROUTE_INVALID_NEXT_HOP_ILB_BACKEND_IP_FORWARDING_DISABLED":
      self = .routeInvalidNextHopIlbBackendIpForwardingDisabled
    case "ROUTE_INVALID_NEXT_HOP_ILB_VIP_NOT_ASSIGNED": self = .routeInvalidNextHopIlbVipNotAssigned
    case "ROUTE_INVALID_NEXT_HOP_VM_WRONG_NETWORK": self = .routeInvalidNextHopVmWrongNetwork
    case "ROUTE_INVALID_NEXT_HOP_VM_NON_PRIMARY_IP": self = .routeInvalidNextHopVmNonPrimaryIp
    case "ROUTE_INVALID_NEXT_HOP_VPN_TUNNEL_NOT_ESTABLISHED":
      self = .routeInvalidNextHopVpnTunnelNotEstablished
    case "ROUTE_INVALID_NEXT_HOP_IP_NOT_ASSIGNED": self = .routeInvalidNextHopIpNotAssigned
    case "ROUTE_INVALID_NEXT_HOP_FORWARDING_RULE_IP_MISMATCH":
      self = .routeInvalidNextHopForwardingRuleIpMismatch
    case "ROUTE_INVALID_NEXT_HOP_FORWARDING_RULE_TYPE_INVALID":
      self = .routeInvalidNextHopForwardingRuleTypeInvalid
    case "IP_UTILIZATION_IP_ALLOCATION_RATIO_HIGH": self = .ipUtilizationIpAllocationRatioHigh
    case "IP_UTILIZATION_IP_ALLOCATION_SUMMARY": self = .ipUtilizationIpAllocationSummary
    case "GKE_NODE_TO_CONTROL_PLANE_BLOCKED_BY_ROUTING_ISSUE":
      self = .gkeNodeToControlPlaneBlockedByRoutingIssue
    case "GKE_NODE_TO_CONTROL_PLANE_PUBLIC_ENDPOINT_BLOCKED_BY_EGRESS_FIREWALL":
      self = .gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall
    case "GKE_NODE_TO_CONTROL_PLANE_PRIVATE_ENDPOINT_BLOCKED_BY_EGRESS_FIREWALL":
      self = .gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall
    case "GKE_CONTROL_PLANE_TO_NODE_BLOCKED_BY_ROUTING_ISSUE":
      self = .gkeControlPlaneToNodeBlockedByRoutingIssue
    case "GKE_CONTROL_PLANE_TO_NODE_BLOCKED_BY_INGRESS_FIREWALL_ON_NODE":
      self = .gkeControlPlaneToNodeBlockedByIngressFirewallOnNode
    case "GKE_IP_UTILIZATION_POD_RANGES_ALLOCATION_HIGH":
      self = .gkeIpUtilizationPodRangesAllocationHigh
    case "GKE_IP_UTILIZATION_POD_RANGES_ALLOCATION_LIMITES_AUTOSCALING":
      self = .gkeIpUtilizationPodRangesAllocationLimitesAutoscaling
    case "GKE_NODE_SERVICE_ACCOUNT_SERVICE_ACCOUNT_DISABLED":
      self = .gkeNodeServiceAccountServiceAccountDisabled
    case "GKE_NODE_SERVICE_ACCOUNT_DEFAULT_SERVICE_ACCOUNT_USED":
      self = .gkeNodeServiceAccountDefaultServiceAccountUsed
    case "GKE_NODE_SERVICE_ACCOUNT_BAD_OAUTH_SCOPES": self = .gkeNodeServiceAccountBadOauthScopes
    case "GKE_IP_MASQ_AGENT_CONFIG_MAP_NOT_COVERING_POD_CIDR":
      self = .gkeIpMasqAgentConfigMapNotCoveringPodCidr
    case "GKE_IP_MASQ_AGENT_CUSTOM_CONFIG_NOT_COVERING_POD_CIDR":
      self = .gkeIpMasqAgentCustomConfigNotCoveringPodCidr
    case "CLOUD_SQL_PRIVATE_IP_BLOCKED_BY_EGRESS_FIREWALL":
      self = .cloudSqlPrivateIpBlockedByEgressFirewall
    case "CLOUD_SQL_PRIVATE_IP_BLOCKED_BY_ROUTING_ISSUE":
      self = .cloudSqlPrivateIpBlockedByRoutingIssue
    case "CLOUD_SQL_PRIVATE_IP_INSTANCE_NOT_RUNNING": self = .cloudSqlPrivateIpInstanceNotRunning
    case "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_SUBNET_ROUTE":
      self = .dynamicRouteShadowedFullyShadowedBySubnetRoute
    case "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_SUBNET_ROUTE":
      self = .dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
    case "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_STATIC_ROUTE":
      self = .dynamicRouteShadowedFullyShadowedByStaticRoute
    case "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_STATIC_ROUTE":
      self = .dynamicRouteShadowedFullyShadowedByPeeringStaticRoute
    case "DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_NCC_SUBNET_ROUTE":
      self = .dynamicRouteShadowedFullyShadowedByNccSubnetRoute
    case "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_SUBNET_ROUTE":
      self = .nccDynamicRouteShadowedFullyShadowedBySubnetRoute
    case "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_PEERING_SUBNET_ROUTE":
      self = .nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
    case "NCC_DYNAMIC_ROUTE_SHADOWED_FULLY_SHADOWED_BY_STATIC_ROUTE":
      self = .nccDynamicRouteShadowedFullyShadowedByStaticRoute
    case "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_SUBNET_ROUTE":
      self = .dynamicRouteShadowedPartiallyShadowedBySubnetRoute
    case "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_PEERING_SUBNET_ROUTE":
      self = .dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute
    case "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_STATIC_ROUTE":
      self = .dynamicRouteShadowedPartiallyShadowedByStaticRoute
    case "DYNAMIC_ROUTE_SHADOWED_PARTIALLY_SHADOWED_BY_PEERING_STATIC_ROUTE":
      self = .dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute
    case "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_FIREWALL_NOT_CONFIGURED":
      self = .loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured
    case "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_RANGE_BLOCKED":
      self = .loadBalancerHealthCheckFirewallHealthCheckRangeBlocked
    case "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_FIREWALL_CONFIG_INCONSISTENT":
      self = .loadBalancerHealthCheckFirewallFirewallConfigInconsistent
    case "LOAD_BALANCER_HEALTH_CHECK_FIREWALL_HEALTH_CHECK_RANGE_PARTIALLY_BLOCKED":
      self = .loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked
    case "LOAD_BALANCER_BEST_PRACTICES_BACKEND_SERVICE_BALANCING_MODE_BREAKS_SESSION_AFFINITY":
      self = .loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity
    case "LOAD_BALANCER_BEST_PRACTICES_BACKEND_SERVICE_HEALTH_CHECK_PORT_MISMATCH":
      self = .loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReportCauseCode/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .routeInvalidNextHopVmIpForwardingDisabled
    case 2: self = .routeInvalidNextHopVmDeleted
    case 3: self = .routeInvalidNextHopVmStopped
    case 4: self = .routeInvalidNextHopIlbMisconfigured
    case 5: self = .routeInvalidNextHopVpnTunnelDeleted
    case 6: self = .routeInvalidNextHopIlbBackendIpForwardingDisabled
    case 7: self = .routeInvalidNextHopIlbVipNotAssigned
    case 8: self = .routeInvalidNextHopVmWrongNetwork
    case 9: self = .routeInvalidNextHopVmNonPrimaryIp
    case 10: self = .routeInvalidNextHopVpnTunnelNotEstablished
    case 11: self = .routeInvalidNextHopIpNotAssigned
    case 12: self = .routeInvalidNextHopForwardingRuleIpMismatch
    case 13: self = .routeInvalidNextHopForwardingRuleTypeInvalid
    case 20: self = .ipUtilizationIpAllocationRatioHigh
    case 21: self = .ipUtilizationIpAllocationSummary
    case 201: self = .gkeNodeToControlPlaneBlockedByRoutingIssue
    case 202: self = .gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall
    case 203: self = .gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall
    case 211: self = .gkeControlPlaneToNodeBlockedByRoutingIssue
    case 212: self = .gkeControlPlaneToNodeBlockedByIngressFirewallOnNode
    case 221: self = .gkeIpUtilizationPodRangesAllocationHigh
    case 222: self = .gkeIpUtilizationPodRangesAllocationLimitesAutoscaling
    case 243: self = .gkeNodeServiceAccountServiceAccountDisabled
    case 244: self = .gkeNodeServiceAccountDefaultServiceAccountUsed
    case 245: self = .gkeNodeServiceAccountBadOauthScopes
    case 251: self = .gkeIpMasqAgentConfigMapNotCoveringPodCidr
    case 252: self = .gkeIpMasqAgentCustomConfigNotCoveringPodCidr
    case 601: self = .cloudSqlPrivateIpBlockedByEgressFirewall
    case 602: self = .cloudSqlPrivateIpBlockedByRoutingIssue
    case 603: self = .cloudSqlPrivateIpInstanceNotRunning
    case 801: self = .dynamicRouteShadowedFullyShadowedBySubnetRoute
    case 802: self = .dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
    case 803: self = .dynamicRouteShadowedFullyShadowedByStaticRoute
    case 804: self = .dynamicRouteShadowedFullyShadowedByPeeringStaticRoute
    case 805: self = .dynamicRouteShadowedPartiallyShadowedBySubnetRoute
    case 806: self = .dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute
    case 807: self = .dynamicRouteShadowedPartiallyShadowedByStaticRoute
    case 808: self = .dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute
    case 821: self = .dynamicRouteShadowedFullyShadowedByNccSubnetRoute
    case 822: self = .nccDynamicRouteShadowedFullyShadowedBySubnetRoute
    case 823: self = .nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute
    case 824: self = .nccDynamicRouteShadowedFullyShadowedByStaticRoute
    case 1001: self = .loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured
    case 1002: self = .loadBalancerHealthCheckFirewallHealthCheckRangeBlocked
    case 1003: self = .loadBalancerHealthCheckFirewallFirewallConfigInconsistent
    case 1004: self = .loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked
    case 1021: self = .loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity
    case 1024: self = .loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .routeInvalidNextHopVmIpForwardingDisabled: return try container.encode(1)
    case .routeInvalidNextHopVmDeleted: return try container.encode(2)
    case .routeInvalidNextHopVmStopped: return try container.encode(3)
    case .routeInvalidNextHopIlbMisconfigured: return try container.encode(4)
    case .routeInvalidNextHopVpnTunnelDeleted: return try container.encode(5)
    case .routeInvalidNextHopIlbBackendIpForwardingDisabled: return try container.encode(6)
    case .routeInvalidNextHopIlbVipNotAssigned: return try container.encode(7)
    case .routeInvalidNextHopVmWrongNetwork: return try container.encode(8)
    case .routeInvalidNextHopVmNonPrimaryIp: return try container.encode(9)
    case .routeInvalidNextHopVpnTunnelNotEstablished: return try container.encode(10)
    case .routeInvalidNextHopIpNotAssigned: return try container.encode(11)
    case .routeInvalidNextHopForwardingRuleIpMismatch: return try container.encode(12)
    case .routeInvalidNextHopForwardingRuleTypeInvalid: return try container.encode(13)
    case .ipUtilizationIpAllocationRatioHigh: return try container.encode(20)
    case .ipUtilizationIpAllocationSummary: return try container.encode(21)
    case .gkeNodeToControlPlaneBlockedByRoutingIssue: return try container.encode(201)
    case .gkeNodeToControlPlanePublicEndpointBlockedByEgressFirewall:
      return try container.encode(202)
    case .gkeNodeToControlPlanePrivateEndpointBlockedByEgressFirewall:
      return try container.encode(203)
    case .gkeControlPlaneToNodeBlockedByRoutingIssue: return try container.encode(211)
    case .gkeControlPlaneToNodeBlockedByIngressFirewallOnNode: return try container.encode(212)
    case .gkeIpUtilizationPodRangesAllocationHigh: return try container.encode(221)
    case .gkeIpUtilizationPodRangesAllocationLimitesAutoscaling: return try container.encode(222)
    case .gkeNodeServiceAccountServiceAccountDisabled: return try container.encode(243)
    case .gkeNodeServiceAccountDefaultServiceAccountUsed: return try container.encode(244)
    case .gkeNodeServiceAccountBadOauthScopes: return try container.encode(245)
    case .gkeIpMasqAgentConfigMapNotCoveringPodCidr: return try container.encode(251)
    case .gkeIpMasqAgentCustomConfigNotCoveringPodCidr: return try container.encode(252)
    case .cloudSqlPrivateIpBlockedByEgressFirewall: return try container.encode(601)
    case .cloudSqlPrivateIpBlockedByRoutingIssue: return try container.encode(602)
    case .cloudSqlPrivateIpInstanceNotRunning: return try container.encode(603)
    case .dynamicRouteShadowedFullyShadowedBySubnetRoute: return try container.encode(801)
    case .dynamicRouteShadowedFullyShadowedByPeeringSubnetRoute: return try container.encode(802)
    case .dynamicRouteShadowedFullyShadowedByStaticRoute: return try container.encode(803)
    case .dynamicRouteShadowedFullyShadowedByPeeringStaticRoute: return try container.encode(804)
    case .dynamicRouteShadowedPartiallyShadowedBySubnetRoute: return try container.encode(805)
    case .dynamicRouteShadowedPartiallyShadowedByPeeringSubnetRoute:
      return try container.encode(806)
    case .dynamicRouteShadowedPartiallyShadowedByStaticRoute: return try container.encode(807)
    case .dynamicRouteShadowedPartiallyShadowedByPeeringStaticRoute:
      return try container.encode(808)
    case .dynamicRouteShadowedFullyShadowedByNccSubnetRoute: return try container.encode(821)
    case .nccDynamicRouteShadowedFullyShadowedBySubnetRoute: return try container.encode(822)
    case .nccDynamicRouteShadowedFullyShadowedByPeeringSubnetRoute: return try container.encode(823)
    case .nccDynamicRouteShadowedFullyShadowedByStaticRoute: return try container.encode(824)
    case .loadBalancerHealthCheckFirewallHealthCheckFirewallNotConfigured:
      return try container.encode(1001)
    case .loadBalancerHealthCheckFirewallHealthCheckRangeBlocked: return try container.encode(1002)
    case .loadBalancerHealthCheckFirewallFirewallConfigInconsistent:
      return try container.encode(1003)
    case .loadBalancerHealthCheckFirewallHealthCheckRangePartiallyBlocked:
      return try container.encode(1004)
    case .loadBalancerBestPracticesBackendServiceBalancingModeBreaksSessionAffinity:
      return try container.encode(1021)
    case .loadBalancerBestPracticesBackendServiceHealthCheckPortMismatch:
      return try container.encode(1024)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
